export const SET_STEPS = "SET_STEPS";
export const SET_CURRENT_STEP = "SET_CURRENT_STEP";
export const SET_CHECKED_ON_VALID = "SET_CHECKED_ON_VALID";
export const SET_CAME_TO_LAST_STEP = "SET_CAME_TO_LAST_STEP";
export const RESET_STEPS = "RESET_STEPS";
export const UPDATE_STATUS_STEPS = "UPDATE_STATUS_STEPS";
export const STOP_STEPS_LOADING = "STOP_STEPS_LOADING";
