export const INIT_TABLE = "INIT_TABLE";
export const DESTROY_TABLE = "DESTROY_TABLE";
export const STRAT_TABLE_LOADING = "STRAT_TABLE_LOADING";
export const STOP_TABLE_LOADING = "STOP_TABLE_LOADING";
export const UPDATE_TABLE = "UPDATE_TABLE";
export const SET_LAST_QUERY_PARAMS_TABLE = "SET_LAST_QUERY_PARAMS_TABLE";
